### ISSUE TITLE
OpenCV custom node

### ISSUE THREAD

**Issue by bnascimento** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#5]
How can we make a LBP cascade multi scale search custom node? For the equivalent of the OpenCV CascadeClassifier class? Can someone point out the right direction?
Cheers

**Comment by rgiduthuri** [comment]
Are you planning to wrap your own implementation into OpenVX user kernel?

**Comment by bnascimento** [comment]
My plan is to wrap the OpenCV implementation of CascadeClassifier into an OpenVX custom node? Maybe into vx_ext_cv project.
Can it be made? Can you point me out a direction of how to do it?
Thank you

**Comment by rgiduthuri** [comment]
Yes. It is possible. Here are general steps to follow:
1. Identify OpenVX data objects for the OpenCV function input/output data
     - e.g., vx_image for Mat, vx_array for std::vector, etc.
2. If the OpenCV function is wrapped inside a class, try using initialize callback and VX_NODE_ATTRIBUTE_LOCAL_DATA_PTR, so that initialization happens only once during the graph verification
3. After that the approach is very similar to any other user kernel. See https://github.com/rgiduthuri/openvx_tutorial/blob/master/tutorial_exercises/solution_exercise4/solution_exercise4.cpp for an example.

Hope that helps.
